#!/bin/bash

function warn() {
    echo -e "\033[1;33m${*}\033[0m"
}

function error() {
    echo -e "\033[1;31m${*}\033[0m"
    exit 1
}

function info() {
    echo -e "\033[1;32m${*}\033[0m"
}

function installed() {
    command -v "$1" >/dev/null 2>&1
}

[ "$(id -u)" -ne 0 ] && error "Please run as root"

# Use CURL_OPTS and WGET_OPTS from environment if set, otherwise allow local override
[ -z "$CURL_OPTS" ] && CURL_OPTS=""
[ -z "$WGET_OPTS" ] && WGET_OPTS=""

if ! installed curl; then
    warn "curl is required, will try to install it"
    if installed apt-get; then
        apt-get update && apt-get install -y curl
    elif installed yum; then
        yum update && yum install -y curl
    elif installed dnf; then
        dnf update && dnf install -y curl
    elif installed zypper; then
        zypper refresh && zypper install -y curl
    elif installed apk; then
        apk upgrade && apk add curl --no-cache
    else
        error "no package manager found, please install curl manually"
    fi
fi

# check curl again
if ! installed curl; then
    error "curl is required, auto installation failed, please install it manually"
fi

# install dependencies
if installed apt; then
    apt-get update && sudo apt install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre2-dev libev-dev automake asciidoc xmlto git pwgen -y
elif installed yum; then
    yum update && yum install -y git gcc make autoconf libtool openssl-devel pcre-devel libev-devel asciidoc xmlto automake pwgen
elif installed dnf; then
    dnf update && dnf install -y git gcc make autoconf libtool openssl-devel pcre-devel libev-devel asciidoc xmlto automake pwgen
elif installed zypper; then
    zypper refresh && zypper install -y git gcc make autoconf libtool openssl-devel pcre-devel libev-devel asciidoc xmlto automake pwgen
elif installed apk; then
    apk upgrade && apk add --no-cache git build-base autoconf libtool openssl-dev pcre-dev libev-dev asciidoc xmlto automake pwgen
else
    error "no package manager found, please install dependencies manually"
fi

ssr_releases_url="https://api.github.com/repos/shadowsocks/shadowsocks-rust/releases"
ssr_version=$(curl ${CURL_OPTS} -sL "$ssr_releases_url" 2>/dev/null | grep "tag_name" | cut -d'"' -f4 | sed 's/[^0-9.]*//g' | head -n1)
[ -z "$ssr_version" ] && error "Failed to get shadowsocks-rust version"
info "found shadowsocks-rust version: $ssr_version"

os=$(uname -s)
case $os in
    Linux | Darwin)
        os=$(echo "$os" | tr '[:upper:]' '[:lower:]')
        ;;
    *)
        error "Unsupported OS: $os"
        ;;
esac

arch=$(uname -m)

case $arch in
    x86_64)
        arch="x86_64"
        ;;
    aarch64 | arm64)
        arch="aarch64"
        ;;
    i*86)
        arch="i686"
        ;;
    *)
        error "Unsupported architecture: $arch"
        ;;
esac

obfs_hosts=(
    "microsoft.com"
    "apple.com"
    "gateway.icloud.com"
)

setup=false
port=
password=""
obfs_host=""
dns_server=""

POSITIONAL=()
while [ $# -gt 0 ]; do
    case "$1" in
        -P | --port)
            port="$2"
            shift 2
            ;;
        -p | --password)
            password="$2"
            shift 2
            ;;
        -o | --obfs-host)
            obfs_host="$2"
            shift 2
            ;;
        -d | --dns-server)
            dns_server="$2"
            shift 2
            ;;
        -s | --setup)
            setup=true
            shift
            ;;
        -4 | --ipv4)
            CURL_OPTS="-4"
            WGET_OPTS="-4"
            shift
            ;;
        -6 | --ipv6)
            CURL_OPTS="-6"
            WGET_OPTS="-6"
            shift
            ;;
        *)
            POSITIONAL+=("$1")
            warn "unknown option $1"
            shift
            ;;
    esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

[ "$setup" == "true" ] && {
    shadowsocks_config_file="/etc/shadowsocks/config.json"
    shadowsocks_libev_config_file="/etc/shadowsocks-libev/config.json"

    [ -f "$shadowsocks_libev_config_file" ] && {
        warn "shadowsocks-libev config file found, will use it"
        shadowsocks_config_file="$shadowsocks_libev_config_file"
    }

    [ -f "$shadowsocks_config_file" ] && {
        password="$(grep 2>/dev/null <"$shadowsocks_config_file" -Eo "\"password\"\s*:\s*\"[^\"]+\"" | cut -d'"' -f4)"
        port="$(grep 2>/dev/null <"$shadowsocks_config_file" -Eo "\"server_port\"\s*:\s*[0-9]+[^,]" | cut -d: -f2 | tr -d ' ')"
        obfs_host="$(grep 2>/dev/null <"$shadowsocks_config_file" -Eo "obfs-host=.*[^,\"]" | cut -d'=' -f2)"
        dns_server="$(grep 2>/dev/null <"$shadowsocks_config_file" -Eo "\"dns_server\"\s*:\s*\"[^\"]+\"" | cut -d'"' -f4)"
    }

    [ -z "$password" ] && {
        warn "password not found in config file, generating a random one"
        password="$(pwgen -ns 32 1 2>/dev/null)" ||
            password="$(busybox pwgen -ns 32 1 2>/dev/null)" ||
            password="$(openssl rand -base64 32 2>/dev/null)" ||
            password="$(busybox mkpasswd -l 32 -C 16 2>/dev/null)" ||
            password="$(tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32 2>/dev/null)"
    }

    [ -z "$port" ] && {
        warn "port not found in config file, generating a random one"
        port=$(shuf -i 10000-65535 -n1 2>/dev/null)
    }

    [ -z "$obfs_host" ] && {
        warn "obfs-host not found in config file, using a random one"
        obfs_host=${obfs_hosts[$(shuf -i 0-3 -n1 2>/dev/null)]}
    }

    [ -z "$dns_server" ] && {
        # check if it's IPV6 only
        v4_route=$(ip -4 route)
        v6_route=$(ip -6 route)
        if [ -z "$v4_route" ] && [ -n "$v6_route" ]; then
            warn "IPv6 only network detected, using Google's public DNS server"
            dns_server="2001:4860:4860::8888"
        else
            warn "using cloudflare's public DNS server"
            dns_server="1.1.1.1"
        fi
    }

    [ -z "$password" ] && error "password required, please specify it with -p or --password"
    [ -z "$port" ] && error "port required, please specify it with -P or --port"
    [ -z "$obfs_host" ] && error "obfs-host required, please specify it with -o or --obfs-host"
}

libc=$(ldd "$(readlink -f /bin/sh)" 2>/dev/null | grep -q 'musl' && echo 'musl' || echo 'gnu')

# shadowsocks-v1.20.1.aarch64-unknown-linux-musl.tar.xz
package_name="shadowsocks-v$ssr_version.$arch-unknown-linux-$libc.tar.xz"
#  shadowsocks-v1.20.1.aarch64-apple-darwin.tar.xz
[ "$os" == "darwin" ] && package_name="shadowsocks-v$ssr_version.$arch-apple-darwin.tar.xz"

ssr_download_url="$(curl ${CURL_OPTS} -sL "$ssr_releases_url" 2>/dev/null | grep "browser_download_url" | grep -Eo "https://.*$package_name" | head -n1)"
[ -z "$ssr_download_url" ] && error "Failed to get shadowsocks-rust download url"
info "found shadowsocks-rust download url: $ssr_download_url"

ssr_temp_dir=$(mktemp -d -t ssr-XXXXXXXXXX 2>/dev/null) || {
    tmp_dir="/tmp/ssr-$(date +%s)"
    mkdir -p "$tmp_dir" || error "Failed to create temporary directory"
}

[ ! -d "$ssr_temp_dir" ] && {
    error "Failed to create temporary directory"
}

ssr_tmp_file="$ssr_temp_dir/$package_name"

[ -f "$ssr_tmp_file" ] && {
    warn "Found existing temporary file, removing it"
    rm -f "$ssr_tmp_file" || error "Failed to remove existing temporary file"
}

curl ${CURL_OPTS} -sL "$ssr_download_url" -o "$ssr_tmp_file" || error "Failed to download shadowsocks-rust"

[ ! -f "$ssr_tmp_file" ] && error "Failed to download shadowsocks-rust"

out_dir="$ssr_temp_dir/out"
mkdir -p "$out_dir" || error "Failed to create output directory"
tar -xJf "$ssr_tmp_file" -C "$out_dir" || error "Failed to extract shadowsocks-rust"
for file in "$out_dir"/*server; do
    [ -x "$file" ] && {
        file_name=$(basename "$file")
        # follow the shadowsocks-libev naming convention, replace ss with ss-
        file_name=${file_name/ss/ss-}
        mv "$file" "/usr/local/bin/$file_name" || error "Failed to move $file_name to /usr/local/bin"
    }
done

"$prefix/bin/ss-server" -V || error "Failed to run ss-server"

rm -rf "$ssr_temp_dir" || error "Failed to remove temporary files"
info "shadowsocks-rust installed successfully"

nproc=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ -z "$nproc" ] && nproc=4

simple_obfs_dir=$(mktemp -d -t simple-obfs-XXXXXXXXXX 2>/dev/null) || {
    simple_obfs_dir="/tmp/simple-obfs-$(date +%s)"
    mkdir -p "$simple_obfs_dir" || error "Failed to create temporary directory"
}

[ ! -d "$simple_obfs_dir" ] && {
    error "Failed to create temporary directory"
}
git clone https://github.com/shadowsocks/simple-obfs.git "$simple_obfs_dir" || error "failed to clone simple-obfs"
[ ! -d "$simple_obfs_dir" ] && error "failed to clone simple-obfs"
pushd "$simple_obfs_dir" >>/dev/null 2>&1 || error "failed to enter simple-obfs directory"
git submodule update --init --recursive
./autogen.sh || error "failed to run autogen.sh for simple-obfs"
# shellcheck disable=SC2046
./configure --disable-documentation --prefix=/usr/local || error "failed to make simple-obfs"
# shellcheck disable=SC2046
make -j$(nproc) || error "failed to make simple-obfs"
make install
popd >>/dev/null 2>&1 || error "failed to leave simple-obfs directory"
info "simple-obfs installed successfully"

[ "$setup" == "true" ] && {
    info "setting up shadowsocks service, will use the following settings:"
    info "port               : $port"
    info "password           : $password"
    info "obfs-host          : $obfs_host"
    info "dns-server         : $dns_server"

    cat <<EOF >config.json
{
        "server"      : "0.0.0.0",
        "server_port" : ${port},
        "password"    : "${password}",
        "timeout"     : 300,
        "method"      : "chacha20-ietf-poly1305",
        "mode"        : "tcp_and_udp",
        "fast_open"   : true,
        "plugin"      : "obfs-server",
        "plugin_opts" : "obfs=http;obfs-host=${obfs_host}"
}
EOF
    # reset shadowsocks_config_file
    shadowsocks_config_file="/etc/shadowsocks/config.json"
    [ ! -d "/etc/shadowsocks/" ] && mkdir -p /etc/shadowsocks/
    mv config.json "$shadowsocks_config_file" 2>/dev/null || sudo mv config.json "$shadowsocks_config_file" 2>/dev/null || error "Failed to move config.json to $shadowsocks_config_file"

    info "shadowsocks config file created successfully"
    shadowsocks_default_file="/etc/default/shadowsocks"
    cat <<EOF >"$shadowsocks_default_file"
# Defaults for shadowsocks initscript
# sourced by /etc/init.d/shadowsocks
# installed at $shadowsocks_default_file by the maintainer scripts

#
# This is a POSIX shell fragment
#
# Note: START, GROUP and MAXFD options are not recognized by systemd.
# Please change those settings in the corresponding systemd unit file.

# Enable during startup?
START=yes

# Configuration file
CONFFILE=$shadowsocks_config_file

# Extra command line arguments
DAEMON_ARGS=-v

# User and group to run the server as
USER=nobody
GROUP=nogroup

# Number of maximum file descriptors
MAXFD=32768
EOF

    shadowsocks_systemd_service_file="/lib/systemd/system/shadowsocks.service"

    cat <<EOF >"$shadowsocks_systemd_service_file"
#  This file is part of shadowsocks.
#
#  shadowsocks is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This file is default for Debian packaging. See also
#  $shadowsocks_default_file for environment variables.

[Unit]
Description=shadowsocks default server service
Documentation=man:shadowsocks(8)
After=network-online.target
Wants=network-online.target

[Service]
Restart=on-failure
RestartSec=5
Type=simple
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
DynamicUser=true
EnvironmentFile=$shadowsocks_default_file
LimitNOFILE=32768
ExecStart=/usr/local/bin/ss-server -c \$CONFFILE \$DAEMON_ARGS

[Install]
WantedBy=multi-user.target
EOF

    systemctl enable shadowsocks.service
    info "shadowsocks service enabled"

    systemctl restart shadowsocks.service
    info "shadowsocks service started"
}
